version: "3.8"

services:
  frontend:
    build: ./web-traficandme-nuveau
    ports:
      - "5181:80"
    depends_on:
      - backend
    env_file:
      - ./web-traficandme-nuveau/.env

  backend:
    build: ./api-traficandme
    ports:
      - "8080:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=http://158.180.239.85:5181,http://localhost:8081,http://mobile.app.url
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/traficandmedb
      - SPRING_DATASOURCE_USERNAME_FILE=/run/secrets/db_user
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db_password
    depends_on:
      - db
    secrets:
      - db_user
      - db_password

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: traficandmedb
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - db_user
      - db_password

volumes:
  db_data:

secrets:
  db_user:
    external: true
  db_password:
    external: true
