version: "3.8"
services:
  frontend:
    build:
      context: ./web-traficandme-nuveau
      args:
        VITE_API_URL: ${API_URL}
        VITE_TOMTOM_API_KEY: ${TOMTOM_API_KEY}
    ports:
      - "5181:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${API_URL}
      - VITE_TOMTOM_API_KEY=${TOMTOM_API_KEY}
    restart: unless-stopped

  backend:
    build: ./api-traficandme
    ports:
      - "8080:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5181,http://localhost:8081}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - TOMTOM_API_KEY=${TOMTOM_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./script/calendar_stats.sql:/docker-entrypoint-initdb.d/calendar_stats.sql
volumes:
  db_data:
