name: Pipline_CI_CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'web-traficandme/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          cd web-traficandme
          npm install
      
      - name: Build Angular app
        run: |
          cd web-traficandme
          npm run build --prod

  build-and-deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Create directory on remote server
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'mkdir -p ~/test'
